---
# Ansible Galaxy collections required for this playbook
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.general
    version: ">=8.0.0"

  - name: ansible.posix
    version: ">=1.5.0"
