---
- name: Install communication/instant messenger apps
  community.general.pacman:
    name: "{{ comms }}"
    state: present
  become: true

- name: Install communication/instant messenger apps from Arch User Repository
  ansible.builtin.shell: |
    set -o pipefail
    pamac build -d --no-confirm {{ item }} | grep "is up to date"
    if [ $? != 0 ]; then
      pamac build --no-confirm {{ item }}
    fi
  loop: "{{ comms_aur }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  tags:
    - aur
    - comms
    - comms-aur
