---
- name: Stop clamav-freshclam to allow manual database update
  ansible.builtin.systemd:
    state: stopped
    name: clamav-freshclam
  become: true
  tags:
    - security
    - clamav

- name: Update ClamAV virus database
  ansible.builtin.command: freshclam
  become: true
  changed_when: true
  tags:
    - security
    - clamav

- name: Start and enable the clamav service
  ansible.builtin.systemd:
    state: started
    name: clamav-daemon
  become: true
  tags:
    - security
    - clamav

- name: Start and enable the freshclam service
  ansible.builtin.systemd:
    state: started
    name: clamav-freshclam
  become: true
  tags:
    - security
    - clamav
