---
- name: Install media tools from Arch User Repository
  ansible.builtin.shell: |
    set -o pipefail
    pamac build -d --no-confirm {{ item }} | grep "is up to date"
    if [ $? != 0 ]; then
      pamac build --no-confirm {{ item }}
    fi
  loop: "{{ media_aur }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  tags:
    - aur
    - media-aur

- name: Install media packages
  community.general.pacman:
    name: "{{ media }}"
    state: present
  become: true
  tags:
    - media
